#!/bin/bash

# Set environment variables for GitHub API
GITHUB_TOKEN=$1           # GitHub token to authenticate the request
PR_NUMBER=$2              # PR number to post the feedback to
REPO_NAME=$3              # Name of the repository (e.g., 'owner/repo')
REVIEW_RESULTS_FILE=$4    # Path to the file containing the review results (e.g., generated by Copilot agent)

# Get the contents of the review feedback
# REVIEW_CONTENT=$(cat $REVIEW_RESULTS_FILE)
REVIEW_CONTENT=$(cat "$REVIEW_RESULTS_FILE")
JSON_BODY=$(jq -n --arg body "$REVIEW_CONTENT" '{body: $body}')

# Define the GitHub API URL for posting comments
API_URL="https://api.github.com/repos/$REPO_NAME/issues/$PR_NUMBER/comments"
echo "API_URL: $API_URL"

# Post feedback as a comment on the PR
# curl -X POST \
#   -H "Authorization: token $GITHUB_TOKEN" \
#   -H "Content-Type: application/json" \
#   -d @- <<EOF
# {
#   "body": "$REVIEW_CONTENT"
# }
# EOF

curl -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Content-Type: application/json" \
  -d "$JSON_BODY" \
  "$API_URL"

echo "GITHUB_TOKEN: $GITHUB_TOKEN"
echo "PR_NUMBER: $PR_NUMBER"
echo "REPO_NAME: $REPO_NAME"
echo "REVIEW_RESULTS_FILE: $REVIEW_RESULTS_FILE"
echo "REVIEW_CONTENT: $REVIEW_CONTENT"
echo "Feedback posted to PR #$PR_NUMBER in repository $REPO_NAME"
