#!/bin/bash

# Set environment variables for GitHub API
GITHUB_TOKEN=$1           # GitHub token to authenticate the request
PR_NUMBER=$2              # PR number to post the feedback to
REPO_NAME=$3              # Name of the repository (e.g., 'owner/repo')
REVIEW_RESULTS_FILE=$4    # Path to the file containing the review results (e.g., generated by Copilot agent)

# Get the contents of the review feedback
REVIEW_CONTENT=$(cat $REVIEW_RESULTS_FILE)

# Define the GitHub API URL for posting comments
API_URL="https://api.github.com/repos/$REPO_NAME/issues/$PR_NUMBER/comments"

# Post feedback as a comment on the PR
curl -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Content-Type: application/json" \
  -d @- <<EOF
{
  "body": "$REVIEW_CONTENT"
}
EOF

echo "Feedback posted to PR #$PR_NUMBER in repository $REPO_NAME"
