name: Auto PR Review for C#

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: HelloWorldApp/HelloWorldApp.csproj
      REPO_NAME: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET SDK (LTS)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: |
          dotnet restore $PROJECT_PATH

      - name: Run Copilot Agent PR Review
        run: CopilotReviewFramework/scripts/run-copilot-agent.sh ${{ github.event.pull_request.number }} pr-review-instructions.md ./review-results.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ env.REPO_NAME }}

      - name: Post PR Review Results
        run: |
          CopilotReviewFramework/scripts/post-pr-feedback.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.number }} ${{ github.repository }} ./review-results.txt
